import { PropsWithChildren } from 'react'
import styles from './layout.module.css'
import Head from 'next/head'
import Link from 'next/link'
import clsx from 'clsx'
import { useRouter } from 'next/router'
import LoginForm from '@/loginForm/loginForm'


export default function Layout({ children }: PropsWithChildren) {
    const { pathname } = useRouter()
    console.log(pathname)
    return (
        <>
            <Head>
                <title>Bookshop</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.page}>
                <header className={styles.header}>
                    <div className={styles.headerContainer}>
                        <h1 className={styles.headerLogo}>Bookshop</h1>
                        <nav>
                            <ul className={styles.headerNavigation}>
                                <li><Link className={clsx(
                                    styles.headerLink,
                                    { [styles.linkSelected]: pathname === "/" },
                                )} href="./">Books</Link></li>
                                <li><Link className={clsx(
                                    styles.headerLink,
                                    { [styles.linkSelected]: pathname === "/audiobooks" },
                                )} href="./audiobooks">Audiobooks</Link></li>
                                <li><Link className={clsx(
                                    styles.headerLink,
                                    { [styles.linkSelected]: pathname === "/gifts" },
                                )} href="./gifts">Stationery & gifts</Link></li>
                                <li><Link className={clsx(
                                    styles.headerLink,
                                    { [styles.linkSelected]: pathname === "/blog" },
                                )} href="./blog">blog</Link></li>
                            </ul>
                        </nav>
                        <div className={styles.userPanel}>
                            <Link href={"./profile"} className={`${styles.headerButton} ${styles.userProfile}` }></Link>
                            <LoginForm />
                            <Link href={"./cart"} className={`${styles.headerButton} ${styles.cart}`}></Link>
                            <p className={styles.headerItemsCount}>3</p>
                        </div>
                    </div>
                </header>
                <main className={styles.main}>
                    {children}
                </main>

            </div>
        </>
    )
}
