import { PropsWithChildren } from 'react'
import styles from './layout.module.css'
import Head from 'next/head'
import Link from 'next/link'
import clsx from 'clsx'
import { useRouter } from 'next/router'
import LoginForm from '@/loginForm/loginForm'
import { useState } from 'react'
import { useAppDispatch, useAppSelector } from '@/utils/hooks'


export default function Layout({ children }: PropsWithChildren) {
    const { pathname } = useRouter();
    const [isOpened, setIsOpened] = useState<boolean>(false);
    const toggleMenu = () => {
        setIsOpened(!isOpened);
    }
    const dispatch = useAppDispatch();
    const isLogged = useAppSelector((state) => state.auth.loggedIn);
    const itemsCount = useAppSelector((state) => state.books.booksInCart.length);

    return (
        <>
            <Head>
                <title>Bookshop</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.page}>
                <header className={styles.header}>
                    <div className={styles.headerContainer}>
                        <h1 className={styles.headerLogo}>Bookshop</h1>
                        <nav>
                            <ul className={styles.headerNavigation}>
                                <li><Link className={clsx(
                                    styles.headerLink,
                                    { [styles.linkSelected]: pathname === "/" },
                                )} href="./">Books</Link></li>
                                <li><Link className={clsx(
                                    styles.headerLink,
                                    { [styles.linkSelected]: pathname === "/audiobooks" },
                                )} href="./audiobooks">Audiobooks</Link></li>
                                <li><Link className={clsx(
                                    styles.headerLink,
                                    { [styles.linkSelected]: pathname === "/gifts" },
                                )} href="./gifts">Stationery & gifts</Link></li>
                                <li><Link className={clsx(
                                    styles.headerLink,
                                    { [styles.linkSelected]: pathname === "/blog" },
                                )} href="./blog">blog</Link></li>
                            </ul>
                        </nav>
                        <div className={styles.userPanel}>
                            {isLogged ? 
                            <Link href={"./profile"} className={`${styles.headerButton} ${styles.userProfile}`}></Link> :
                            <button className={`${styles.headerButton} ${styles.userProfile}`} onClick={toggleMenu}></button>
                            }
                            
                            {isOpened && <LoginForm setIsOpened={setIsOpened}/>}
                            <Link href={"./cart"} className={`${styles.headerButton} ${styles.cart}`}></Link>
                            {itemsCount && <p className={styles.headerItemsCount}>{itemsCount}</p>}
                        </div>
                    </div>
                </header>
                <main className={styles.main}>
                    {children}
                </main>

            </div>
        </>
    )
}
